In [1]:
#conda install -c anaconda seaborn

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns


## LOAD

In [3]:
df = pd.read_csv("../data/200418COVID19MEXICO_CLEAN_P.csv")
df.head()

ORIGEN  SECTOR  ENTIDAD_UM  SEXO  ENTIDAD_NAC  ENTIDAD_RES  MUNICIPIO_RES  \
0       2       9          15     1           15           15             37   
1       2      12           9     1           15            9              3   
2       2       9          28     2           16           28             32   
3       2      12           9     2            9            9             13   
4       1       3          15     2           15           15            106   

   TIPO_PACIENTE FECHA_INGRESO FECHA_SINTOMAS  ... HIPERTENSION  OTRA_COM  \
0              2    2020-04-09     2020-03-28  ...            2         2   
1              1    2020-04-16     2020-04-02  ...            2         2   
2              1    2020-04-06     2020-04-04  ...            2         2   
3              1    2020-04-17     2020-04-15  ...            2         2   
4              1    2020-04-16     2020-04-14  ...            2         2   

   CARDIOVASCULAR  OBESIDAD  RENAL_CRONICA  TABAQUISMO  OTRO_CASO  RESULTADO  \
0               2         2              2           2          2          1   
1               2         1              2           2          2          2   
2               2         2              2           2          1          1   
3               2         2              2           2          1          3   
4               2         1              2           2          1          3   

   MIGRANTE  UCI  
0        99    1  
1        99   97  
2        99   97  
3        99   97  
4        99   97  

[5 rows x 31 columns]

In [4]:
df_copy = df.copy()

### FECHAS

In [5]:
df_copy.FECHA_DEF.replace({"2020-05-22": "2019-01-01"}, inplace=True)

In [6]:
dates = ["FECHA_INGRESO", "FECHA_SINTOMAS", "FECHA_DEF"]

In [7]:
df_copy.FECHA_INGRESO = pd.to_datetime(df_copy.FECHA_INGRESO, format='%Y-%m-%d')
df_copy.FECHA_INGRESO.head(1)

0   2020-04-09
Name: FECHA_INGRESO, dtype: datetime64[ns]

In [8]:
df_copy.FECHA_SINTOMAS = pd.to_datetime(df_copy.FECHA_SINTOMAS, format='%Y-%m-%d')
df_copy.FECHA_SINTOMAS.head(1)

0   2020-03-28
Name: FECHA_SINTOMAS, dtype: datetime64[ns]

In [9]:
df_copy.FECHA_DEF = pd.to_datetime(df_copy.FECHA_DEF, format='%Y-%m-%d')
df_copy.FECHA_DEF.head(1)

0   2019-01-01
Name: FECHA_DEF, dtype: datetime64[ns]

In [10]:
df_copy[dates].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49158 entries, 0 to 49157
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   FECHA_INGRESO   49158 non-null  datetime64[ns]
 1   FECHA_SINTOMAS  49158 non-null  datetime64[ns]
 2   FECHA_DEF       49158 non-null  datetime64[ns]
dtypes: datetime64[ns](3)
memory usage: 1.1 MB


`FECHA_DEF` 

El valor `2019-01-01` aparece 97.45% de las veces. Suponiendo que fue porque no hay muerto y se recuperaron

`DIAS_DEF_INGRESO` 

In [11]:
df_copy.FECHA_DEF.iloc[0]

Timestamp('2019-01-01 00:00:00')

In [12]:
df_copy.FECHA_INGRESO.iloc[0]

Timestamp('2020-04-09 00:00:00')

In [13]:
df_copy.FECHA_DEF.iloc[0] - df_copy.FECHA_INGRESO.iloc[0]  

Timedelta('-464 days +00:00:00')

In [14]:
(df_copy.FECHA_DEF - df_copy.FECHA_INGRESO).dt.days.head(1)

0   -464
dtype: int64

In [15]:
df_copy["DIAS_DEF_INGRESO"] =  (df_copy.FECHA_DEF - df_copy.FECHA_INGRESO).dt.days
df_copy["DIAS_DEF_INGRESO"].head(3)

0   -464
1   -471
2   -461
Name: DIAS_DEF_INGRESO, dtype: int64

In [16]:
df_copy["DIAS_DEF_INGRESO"] = df_copy["DIAS_DEF_INGRESO"].clip(lower=0)
df_copy["DIAS_DEF_INGRESO"].value_counts().head()

0    48101
1      183
2      135
3      112
5       99
Name: DIAS_DEF_INGRESO, dtype: int64

`DIAS_SINTOMAS_INGRESO` 

In [17]:
df_copy.FECHA_INGRESO.iloc[0]

Timestamp('2020-04-09 00:00:00')

In [18]:
df_copy.FECHA_SINTOMAS.iloc[0]

Timestamp('2020-03-28 00:00:00')

In [19]:
df_copy.FECHA_INGRESO.iloc[0] - df_copy.FECHA_SINTOMAS.iloc[0]  

Timedelta('12 days 00:00:00')

In [20]:
df_copy["DIAS_SINTOMAS_INGRESO"] = (df_copy.FECHA_INGRESO - df_copy.FECHA_SINTOMAS).dt.days
df_copy["DIAS_SINTOMAS_INGRESO"].head(3)

0    12
1    14
2     2
Name: DIAS_SINTOMAS_INGRESO, dtype: int64

In [21]:
df_copy["DIAS_SINTOMAS_INGRESO"] = df_copy["DIAS_SINTOMAS_INGRESO"].clip(lower=0)
df_copy["DIAS_SINTOMAS_INGRESO"].value_counts().head()

2    7331
0    7287
1    6738
3    6682
4    5533
Name: DIAS_SINTOMAS_INGRESO, dtype: int64

`DIAS_DEF_SINTOMAS` 

In [22]:
df_copy.FECHA_DEF.iloc[0]

Timestamp('2019-01-01 00:00:00')

In [23]:
df_copy.FECHA_SINTOMAS.iloc[0]

Timestamp('2020-03-28 00:00:00')

In [24]:
df_copy.FECHA_DEF.iloc[0] - df_copy.FECHA_SINTOMAS.iloc[0]  

Timedelta('-452 days +00:00:00')

In [25]:
df_copy["DIAS_DEF_SINTOMAS"] = (df_copy.FECHA_DEF - df_copy.FECHA_SINTOMAS).dt.days
df_copy["DIAS_DEF_SINTOMAS"].head(3)

0   -452
1   -457
2   -459
Name: DIAS_DEF_SINTOMAS, dtype: int64

In [26]:
df_copy["DIAS_DEF_SINTOMAS"] = df_copy["DIAS_DEF_SINTOMAS"].clip(lower=0)
df_copy["DIAS_DEF_SINTOMAS"].value_counts().head()

0    47930
5      108
7      106
6      100
9       90
Name: DIAS_DEF_SINTOMAS, dtype: int64

In [27]:
df_copy.drop(labels=["FECHA_INGRESO"], axis=1, inplace=True)

In [28]:
df_copy.drop(labels=["FECHA_DEF"], axis=1, inplace=True)

In [29]:
df_copy.drop(labels=["FECHA_SINTOMAS"], axis=1, inplace=True)

In [30]:
df_copy.shape

(49158, 31)

## WARNINGS

`INTUBADO`
El valor `97` aparece 76.56% de las veces.

In [31]:
df_copy.drop(df_copy[df_copy.INTUBADO == 99].index, axis=0, inplace=True)

In [32]:
df_copy.INTUBADO.unique()

array([ 2, 97,  1])

In [33]:
df_copy.shape

(49150, 31)

`NEUMONIA`
El valor 99 aparece 0.0162% de las veces.

In [34]:
df_copy.drop(df_copy[df_copy.NEUMONIA == 99].index, axis=0, inplace=True)

In [35]:
df_copy.NEUMONIA.unique()

array([1, 2])

In [36]:
df_copy.shape

(49142, 31)

`EMBARAZO`
El valor 99 aparece 0.0162% de las veces.

In [37]:
df_copy.drop(df_copy[df_copy.EMBARAZO == 98].index, axis=0, inplace=True)

In [38]:
df_copy.drop(df_copy[df_copy.EMBARAZO == 1].index, axis=0, inplace=True)

`EMBARAZO`
El valor 99 aparece 0.0162% de las veces.

In [39]:
df_copy.EMBARAZO.unique()

array([ 2, 97])

In [40]:
df_copy.shape

(48492, 31)

`HABLA_LENGUA_INDIG`
El valor `2` aparece 97.48% de las veces.

In [41]:
df_copy.drop(labels=["HABLA_LENGUA_INDIG"], axis=1, inplace=True)

In [42]:
df_copy.shape

(48492, 30)

`DIABETES`
El valor 98 aparece 0.33363% de las veces. 

In [43]:
df_copy.drop(df_copy[df_copy.DIABETES == 98].index, axis=0, inplace=True)

In [44]:
df_copy.DIABETES.unique()

array([1, 2])

In [45]:
df_copy.shape

(48343, 30)

`EPOC`
El valor 98 aparece 0.33363% de las veces. 

In [46]:
df_copy.drop(df_copy[df_copy.EPOC == 98].index, axis=0, inplace=True)

In [47]:
df_copy.EPOC.unique()

array([2, 1])

In [48]:
df_copy.shape

(48322, 30)

`ASMA`
El valor 98 aparece 0.3315% de las veces.

In [49]:
df_copy.drop(df_copy[df_copy.ASMA == 98].index, axis=0, inplace=True)

In [50]:
df_copy.ASMA.unique()

array([2, 1])

In [51]:
df_copy.shape

(48313, 30)

`INMUSUPR`
El valor 98 aparece 0.3417% de las veces. 

In [52]:
df_copy.drop(df_copy[df_copy.INMUSUPR == 98].index, axis=0, inplace=True)

In [53]:
df_copy.INMUSUPR.unique()

array([2, 1])

In [54]:
df_copy.shape

(48300, 30)

`HIPERTENSION`
El valor 98 aparece 0.3153% de las veces. 

In [55]:
df_copy.drop(df_copy[df_copy.HIPERTENSION == 98].index, axis=0, inplace=True)

In [56]:
df_copy.INMUSUPR.unique()

array([2, 1])

In [57]:
df_copy.shape

(48293, 30)

`OTRA_COM`
El valor 98 aparece 0.4190% de las veces

In [58]:
df_copy.drop(df_copy[df_copy.OTRA_COM == 98].index, axis=0, inplace=True)

In [59]:
df_copy.OTRA_COM.unique()

array([2, 1])

In [60]:
df_copy.shape

(48245, 30)

`CARDIOVASCULAR`
El valor 98 aparece 0.3336% de las veces. 

In [61]:
df_copy.drop(df_copy[df_copy.CARDIOVASCULAR == 98].index, axis=0, inplace=True)

In [62]:
df_copy.CARDIOVASCULAR.unique()

array([2, 1])

In [63]:
df_copy.shape

(48238, 30)

`OBESIDAD`
El valor 98 aparece 0.2949% de las veces. 

In [64]:
df_copy.drop(df_copy[df_copy.OBESIDAD == 98].index, axis=0, inplace=True)

In [65]:
df_copy.OBESIDAD.unique()

array([2, 1])

In [66]:
df_copy.shape

(48232, 30)

`RENAL_CRONICA`
El valor 98 aparece 0.3234% de las veces.

In [67]:
df_copy.drop(df_copy[df_copy.RENAL_CRONICA == 98].index, axis=0, inplace=True)

In [68]:
df_copy.RENAL_CRONICA.unique()

array([2, 1])

In [69]:
df_copy.shape

(48224, 30)

`TABAQUISMO`
El valor 98 aparece 0.3315% de las veces. 

In [70]:
df_copy.drop(df_copy[df_copy.TABAQUISMO == 98].index, axis=0, inplace=True)

In [71]:
df_copy.TABAQUISMO.unique()

array([2, 1])

In [72]:
df_copy.shape

(48212, 30)

`MIGRANTE`
El valor 99 aparece 99.48% de las veces. 

In [73]:
df_copy.drop(labels=["MIGRANTE"], axis=1, inplace=True)

In [74]:
df_copy.shape

(48212, 29)

`UCI`
El valor 97 aparece 76.56% de las veces. 

In [75]:
df_copy.drop(labels=["UCI"], axis=1, inplace=True)

In [76]:
df_copy.shape

(48212, 28)

`DIAS_DEF_SINTOMAS`
El valor `0` aparece 0.0467% de las veces. 

In [77]:
(df_copy[df_copy.DIAS_DEF_SINTOMAS == 0].DIAS_DEF_SINTOMAS.value_counts().iloc[0]/df_copy.shape[0])*100

97.5089189413424

In [78]:
df_copy.drop(labels=["DIAS_DEF_SINTOMAS"], axis=1, inplace=True)

In [79]:
df_copy.shape

(48212, 27)

`DIAS_DEF_INGRESO`
El valor `0` aparece 0.0467% de las veces. 

In [80]:
(df_copy[df_copy.DIAS_DEF_INGRESO == 0].DIAS_DEF_INGRESO.value_counts().iloc[0]/df_copy.shape[0])*100

97.85530573301253

In [81]:
df_copy.drop(labels=["DIAS_DEF_INGRESO"], axis=1, inplace=True)

In [82]:
df_copy.shape

(48212, 26)

In [83]:
df_copy.head()

ORIGEN  SECTOR  ENTIDAD_UM  SEXO  ENTIDAD_NAC  ENTIDAD_RES  MUNICIPIO_RES  \
0       2       9          15     1           15           15             37   
1       2      12           9     1           15            9              3   
2       2       9          28     2           16           28             32   
3       2      12           9     2            9            9             13   
4       1       3          15     2           15           15            106   

   TIPO_PACIENTE  INTUBADO  NEUMONIA  ...  INMUSUPR  HIPERTENSION  OTRA_COM  \
0              2         2         1  ...         2             2         2   
1              1        97         2  ...         2             2         2   
2              1        97         2  ...         2             2         2   
3              1        97         2  ...         2             2         2   
4              1        97         2  ...         2             2         2   

   CARDIOVASCULAR  OBESIDAD  RENAL_CRONICA  TABAQUISMO  OTRO_CASO  RESULTADO  \
0               2         2              2           2          2          1   
1               2         1              2           2          2          2   
2               2         2              2           2          1          1   
3               2         2              2           2          1          3   
4               2         1              2           2          1          3   

   DIAS_SINTOMAS_INGRESO  
0                     12  
1                     14  
2                      2  
3                      2  
4                      2  

[5 rows x 26 columns]

In [84]:
print("df: ", df.shape)
print("df_copy: ", df_copy.shape)
print("diferencia: (", df.shape[0] - df_copy.shape[0], ",", df.shape[1] - df_copy.shape[1], ")")
print("porcentaje: ", ((df.shape[0] - df_copy.shape[0])*100)/df.shape[0], "%")

df:  (49158, 31)
df_copy:  (48212, 26)
diferencia: ( 946 , 5 )
porcentaje:  1.9244070141177427 %


In [85]:
df_copy.to_csv("../data/200418COVID19MEXICO_CLEAN_S.csv", index=False)